# Generated by Django 5.2.8 on 2025-11-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=100)),
                ('apk_file', models.FileField(upload_to='apkgen/')),
            ],
        ),
    ]
