# Generated by Django 5.2.8 on 2025-11-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service or account', max_length=255)),
                ('category', models.CharField(choices=[('email', 'Email Account'), ('replit', 'Replit Account'), ('ssh', 'SSH Key'), ('other', 'Other')], default='other', max_length=20)),
                ('username', models.CharField(blank=True, help_text='Username or Email', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Password or Key (stored as plain text)', max_length=255)),
                ('payment_status', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10)),
                ('paid_by', models.CharField(blank=True, help_text='Who pays for this', max_length=255)),
                ('card_used', models.CharField(blank=True, help_text='Which card was used', max_length=255)),
                ('payment_start_date', models.DateField(blank=True, null=True)),
                ('reminder_days_before', models.IntegerField(blank=True, help_text='Days to remind before renewal/expiry', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
