# Generated by Django 5.2.8 on 2025-11-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
